/** Central Flux action type constants */
export const ActionTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  UPDATE_AUTH_USER: 'UPDATE_AUTH_USER',
  LOGOUT: 'LOGOUT',
  UPDATE_ROLE: 'UPDATE_ROLE',
  UPDATE_PERMISSION: 'UPDATE_PERMISSION',
  OPEN_STUDENT_MODAL: 'OPEN_STUDENT_MODAL',
  LOAD_STUDENT_LIST: 'LOAD_STUDENT_LIST',
  SET_NATIONALITIES_LIST: 'SET_NATIONALITIES_LIST',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  UPDATE_LOADING: 'UPDATE_LOADING',
  UPDATE_NEW_FAMILY_MEMBER: 'UPDATE_NEW_FAMILY_MEMBER',
};
